const pixar = `Pixar Animation Studios (commonly known as Pixar (/ˈpɪksɑːr/) and stylized as P I X A R) is an American computer animation studio known for its critically and commercially successful computer animated feature films. It is based in Emeryville, California, United States. Since 2006, Pixar has been a subsidiary of Walt Disney Studios, which is another studio owned by The Walt Disney Company.

Pixar started in 1979 as part of the Lucasfilm computer division, known as the Graphics Group, before its spin-off as a corporation in 1986, with funding from Apple co-founder Steve Jobs, who became its majority shareholder.[2] Disney purchased Pixar in January 2006 at a valuation of $7.4+ billion by converting each share of Pixar stock to 2.3 shares of Disney stock.[4][5] Pixar is best known for its feature films, technologically powered by RenderMan, the company's own implementation of the industry-standard RenderMan Interface Specification image-rendering API. The studio's mascot is Luxo Jr., a desk lamp from the studio's 1986 short film of the same name.

Pixar has produced 26 feature films, starting with Toy Story (1995), which is the first fully computer-animated feature film; its most recent film was Lightyear (2022). The studio has also produced many short films. As of July 2019, its feature films have earned approximately $14 billion at the worldwide box office,[6] with an average worldwide gross of $680 million per film.[7] Toy Story 3 (2010), Finding Dory (2016), Incredibles 2 (2018), and Toy Story 4 (2019) are all among the 50 highest-grossing films of all time, with Incredibles 2 being the fourth-highest-grossing animated film of all time, with a gross of $1.2 billion; the other three also grossed over $1 billion. Moreover, 15 of Pixar's films are in the 50 highest-grossing animated films of all time.

Pixar has earned 23 Academy Awards, 10 Golden Globe Awards, and 11 Grammy Awards, along with numerous other awards and acknowledgments. Its films are frequently nominated for the Academy Award for Best Animated Feature, since its inauguration in 2001, with eleven winners being Finding Nemo (2003), The Incredibles (2004), Ratatouille (2007), WALL-E (2008), Up (2009), Toy Story 3 (2010), Brave (2012), Inside Out (2015), Coco (2017), Toy Story 4 (2019), and Soul (2020); the five nominated without winning are Monsters, Inc. (2001), Cars (2006), Incredibles 2 (2018), Onward (2020), and Luca (2021). Up and Toy Story 3 were also nominated for the more competitive and inclusive Academy Award for Best Picture.

On February 10, 2009, Pixar executives John Lasseter, Brad Bird, Pete Docter, Andrew Stanton, and Lee Unkrich were presented with the Golden Lion award for Lifetime Achievement by the Venice Film Festival. The physical award was ceremoniously handed to Lucasfilm's founder, George Lucas. `;

const disney = `The Walt Disney Company, commonly known as Disney (/ˈdɪzni/),[4] is an American, multinational, mass media and entertainment conglomerate that is headquartered at the Walt Disney Studios complex in Burbank, California. Disney was founded on October 16, 1923, by brothers Walt and Roy O. Disney as Disney Brothers Studio; it also operated under the names Walt Disney Studio and Walt Disney Productions before changing its name to The Walt Disney Company in 1986. Early in its existence, the company established itself as a leader in the animation industry, with the creation of the widely popular character Mickey Mouse, who first appeared in Steamboat Willie, which used synchronized sound, to becoming the first post-produced sound cartoon.[5] The character would go on to the become the company's mascot.

After becoming a major success by the early 1940s, the company diversified into live-action films, television, and theme parks in the 1950s. Following Walt Disney's death in 1966, the company's profits, especially in the animation division, began to decline. Once Disney's shareholders voted Michael Eisner as the head of the company in 1984, it became overwhelmingly successful during a period called the Disney Renaissance. In 2005, under new CEO Bob Iger, the company started to expand and acquire other corporations. Bob Chapek became the head of Disney in 2020 after Iger's retirement. Chapek was ousted in 2022 and Iger was reinstated as CEO.

Since the 1980s, Disney has created and acquired corporate divisions to market more-mature content than is typically associated with its family-oriented brands. The company is known for its film-studio division Walt Disney Studios, which includes Walt Disney Pictures, Walt Disney Animation Studios, Pixar, Marvel Studios, Lucasfilm, 20th Century Studios, 20th Century Animation, and Searchlight Pictures. Disney's other main business units include divisions in television, broadcasting, streaming media, theme park resorts, consumer products, publishing, and international operations. Through these divisions, Disney owns and operates the ABC broadcast network; cable television networks such as Disney Channel, ESPN, Freeform, FX, and National Geographic; publishing, merchandising, music, and theater divisions; direct-to-consumer streaming services such as Disney+, Star+, ESPN+, Hulu, and Hotstar; and Disney Parks, Experiences and Products, which includes several theme parks, resort hotels, and cruise lines around the world.

Disney is one of the biggest and best-known companies in the world, and has been ranked number 53 on the 2022 Fortune 500 list of biggest companies in the United States by revenue. Since its founding, the company has won 135 Academy Awards, 26 of which have been awarded to Walt. The company has been said to have produced some of the greatest films of all time, as well as revolutionizing the theme park industry. Disney has been criticized for supposed plagiarism, depicting racial stereotypes in the past, and both including and lacking LGBT-related elements in its films. The company, which has been public since 1940, trades on the New York Stock Exchange (NYSE) with ticker symbol DIS and has been a component of the Dow Jones Industrial Average since 1991. In August 2020, just under two-thirds of the stock was owned by large financial institutions.`;

const news = 'https://news.ycombinator.com/';